#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon Dec 02 20:16:37 +03 2024
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim fms_top_sim_behav -key {Behavioral:sim_1:Functional:fms_top_sim} -tclbatch fms_top_sim.tcl -view /home/it/chipxprt/DSD/DSD_lab07/Task4/Task4/fms_top_sim_behav.wcfg -log simulate.log"
xsim fms_top_sim_behav -key {Behavioral:sim_1:Functional:fms_top_sim} -tclbatch fms_top_sim.tcl -view /home/it/chipxprt/DSD/DSD_lab07/Task4/Task4/fms_top_sim_behav.wcfg -log simulate.log

